# Generated by Django 4.2.7 on 2026-02-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lowstockalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sold_at']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-received_date'], 'verbose_name_plural': 'Stock'},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
